name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    # Runs every hour	    - cron: '0 * * * *' # Runs every hour, on the hour
    - cron: '0 * * * *'	  
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/vadorequest, https://medium.com/feed/@vadorequest, https://stackoverflow.com/feeds/user/2391795"
