name: Latest stack overflow activity
on:
  push: # Run workflow automatically, on push
  schedule: # Run workflow automatically, on schedule
    # Runs every hour	    - cron: '0 * * * *' # Runs every hour, on the hour
    - cron: '0 * * * *'	  
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          feed_list: "https://stackoverflow.com/feeds/user/2391795"
